### ISSUE TITLE
Using lattice in tf serving

### ISSUE THREAD

**Issue by fabrol** [tensorflow/lattice#19]
Currently when trying to serve a lattice model with tf serving, I run into an op that isn't supported in the serving kernel

``
...
2018-03-01 23:45:59.827196: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:284] Loading SavedModel: fail. Took 429225 microseconds.
2018-03-01 23:45:59.828892: E tensorflow_serving/util/retrier.cc:38] Loading servable: {name: default version: 1519947547} failed: Not found: Op type not registered 'PwlIndexingCalibrator' in binary running on dsexperiment-prod-0fe24ce9bf2552633. Make sure the Op and Kernel are registered in the binary running in this process.
``

Both tf and tf-serving on the system are at version 1.5.0. Are lattice models not supported with serving yet ? If they are, could you point me to how to make it happen.

**Comment by si-you** [comment]
Lattice models are not supported by tf-serving by default. If you want to use lattice models in tensorflow serving, you will need to build tensorflow serving's model_server binary with our C++ kernels. Here's one way to do this.

Step 1) Clone TensorFlow serving git repo.

Step 2) Add additional dependencies to tensorflow_model_server cc binary rule in tensorflow_serving/model_servers/BUILD something like
`@org_tensorflow_lattice//tensorflow_lattice:tensorflow_lattice_cc`

Step 3) Now we need to let bazel know where to find @org_tensorflow_lattice. 
Firstly, let us create a macro in serving/repo.bzl

```
tensorflow_http_archive = repository_rule(
    implementation=_tensorflow_http_archive,
    attrs={
        "git_commit": attr.string(mandatory=True),
        "sha256": attr.string(mandatory=True),
    })

def _tensorflow_lattice_http_archive(ctx):
  git_commit = ctx.attr.git_commit
  sha256 = ctx.attr.sha256

  strip_prefix = "lattice-%s" % git_commit
  # strip_prefix = ""
  urls = [
      "https://mirror.bazel.build/github.com/tensorflow/lattice/archive/%s.tar.gz" % git_commit,
      "https://github.com/tensorflow/lattice/archive/%s.tar.gz" % git_commit,
  ]
  ctx.download_and_extract(
      urls,
      "",
      sha256,
      "",
      strip_prefix)
```

Now let's actually define @org_tensorflow_lattice repo in WORKSPACE using this macro.

```
load("//tensorflow_serving:repo.bzl", "tensorflow_lattice_http_archive")

tensorflow_lattice_http_archive(
    name = "org_tensorflow_lattice",
    sha256 = "f4d8e7a34730ff8b5f896bb213d7a23945af8ec4a7dbc88124658a48eadb9849",
    git_commit = "45336f10ee37326e2e719645d4e1eeb8ce01c523",
)
```

Here git_commit points to the git commit number in the most recent commit number in tensorflow/lattice.git, and sha256 is generated by fetching the code & computing sha256 in my machine. (In fact, tensorflow serving's WORKSPACE explains how to do this for TensorFlow git repo.)

Step 4) Build tensorflow_model_server
```
bazel build -c opt tensorflow_serving/model_servers:tensorflow_model_server
```

Step 5) Use this model server
```
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server \
  --port=<number you want to use> \
  --model_base_path=<path to your exported model>
```

Note that this is not the only way. As long as you build tensorflow model server linked with our tensorflow_lattice_cc, you're good to go :).

**Comment by fabrol** [comment]
Thanks for info ! I got it to load the model successfully. Will try and integrate serving with pandas next.

Small typo in the code you have above - for the info we add to repo.bzl, I think you meant to add the http archive for lattice not base tensorflow which already exists :) 

``

    tensorflow_lattice_http_archive = repository_rule(
    implementation=_tensorflow_lattice_http_archive,
    attrs={
        "git_commit": attr.string(mandatory=True),
        "sha256": attr.string(mandatory=True),
    })``

**Comment by fabrol** [comment]
While this method works for tensorflow_serving, lattice models can't be used for a similar reason with the default tensorflow model predictor class.
`https://github.com/tensorflow/tensorflow/blob/32ffc5a81eee8c39bbe71536212a773b1ffd4eb2/tensorflow/contrib/predictor/saved_model_predictor.py#L114`

I get a similar op_def error. 
```
from tensorflow.contrib import predictor

predict_fn = predictor.from_saved_model('notebook_root/exports/1520123544/')
...
KeyError: u'PwlIndexingCalibrator'
```

Would the suggestion be to rebuild tensorflow just to get the ability to save and then predict using any lattice model or am I missing something ?

**Comment by si-you** [comment]
I don't think you need to rebuild everything from the scratch. Your python only imports tensorflow, so your python has no idea where to find those C++ kernels.
Could you try this and check whether it's working or not?

```python
from tensorflow.contrib import predictor
import tensorflow_lattice as tfl

predict_fn = predictor.from_saved_model('....')
```
