### ISSUE TITLE
Image links broken in lattice/g3doc/tutorial/index.md

### ISSUE THREAD

**Issue by paulsendavidjay** [tensorflow/lattice#28]
Image links appear to be broken

**Comment by mmilanifard** [comment]
Seems to work for me. Also works in incognito. Might be an issue with browser or your settings?

![screencapture-github-tensorflow-lattice-blob-master-g3doc-tutorial-index-md-2018-09-03-16_49_13](https://user-images.githubusercontent.com/32752864/45003633-61c5a500-af99-11e8-890b-1287fc796eff.png)
