### ISSUE TITLE
uci_census.py with calibrated_dnn fails

### ISSUE THREAD

**Issue by adrianomoala** [tensorflow/lattice#29]
Hi, first of all I would like to say that TF Lattice is amazing, thanks!!!.

I've tried to run uci_census.py and it works perfectly with all types of models, but 'calibrated_dnn'.

The error happened at line 420:
 (output, _, _, regularization) = tfl.input_calibration_layer_from_hparams(
        features, feature_columns, hparams, quantiles_dir)

I inspected the function tfl.input_calibration_layer_from_hparams and it expects only columns_to_tensor and hparams, but the line 420 provides 3 parameters (features, feature_columns, hparams) 

I used pip and by default it installs tensorflow==1.11 and tensorflow_lattice==0.98. 

Thanks

**Comment by mmilanifard** [comment]
Thanks for reporting this. We changed the API a few month ago, but forgot to update the example code. A fix is coming up in the next release (with TF 1.12).

**Comment by adrianomoala** [comment]
Ok, thanks.
