### ISSUE TITLE
TensorFlow 2.0 plan

### ISSUE THREAD

**Issue by si-you** [tensorflow/lattice#30]
Is there any plan for tensorflow 2.0 release?
I heard that the eager mode will be default in TF 2.0, but not sure TF lattice is ready for it.

Thank you!

**Comment by mmilanifard** [comment]
We are actively working towards a release for TF 2.0.

**Comment by si-you** [comment]
thank you!

**Comment by vishnuapp** [comment]
Wanted to check to see if there is an ETA on TF 2.0.
Thanks.

**Comment by mmilanifard** [comment]
We will be releasing an update to the current code base with tf.compat.v1 in a week or so, which should make it usable in graph mode under TF 2.0 release. The new library with eager support and Keras layers is on its way and will hopefully be open sourced by the end of this quarter.

**Comment by vishnuapp** [comment]
Thank you.

**Comment by uve** [comment]
hello @mmilanifard, could you please provide any ETA for lattice+tf2.0?

**Comment by mmilanifard** [comment]
Sorry for the long delays on this. RFC is out and we are hoping for a release by mid Jan. We welcome any feedback on the design.
PR: https://github.com/tensorflow/community/pull/186
[RFC doc](https://github.com/tensorflow/community/blob/0e514fea1e15ccf63f4254b88cb40a2495d5f6d7/rfcs/20191206-tensorflow-lattice-v2.md)
