### ISSUE TITLE
How to add sample weights to tensorflow_lattice.calibrated_etl_classifier and other estimators

### ISSUE THREAD

**Issue by fuyanlu1989** [tensorflow/lattice#39]
In tensorflow.estimator.DNNRegressor, we can add sample weights by argument `weight_column`. But we didn't find this for tensorflow lattice estimators. Is it a missing feature? Could you please add this feature?

**Comment by mmilanifard** [comment]
I'm not sure if I understand your question. `calibrated_etl_regressor` has a `weight_column` argument. Same for all other estimators.

https://github.com/tensorflow/lattice/blob/master/tensorflow_lattice/python/estimators/calibrated_etl.py#L568

**Comment by fuyanlu1989** [comment]
Thanks! I didn't find it in examples. And not found instruction online. Not dig into the source code.
