### ISSUE TITLE
 Example for monotonocity with linear embedding layer 

### ISSUE THREAD

**Issue by Gevorg-Minasyan** [tensorflow/lattice#40]
In the [Deep Lattice Networks and Partial Monotonic Functions](https://ai.google/research/pubs/pub46327) article there is a so-called linear embedding layer for monotonic and non-monotonic inputs, for which there is no example and also there is no such layer in API Docs.

**Comment by mmilanifard** [comment]
TFL 2.0 includes the linear layer with norm bounds and better documentation. RFC is out and we are hoping for a release by mid Jan.
PR: https://github.com/tensorflow/community/pull/186
[RFC doc](https://github.com/tensorflow/community/blob/0e514fea1e15ccf63f4254b88cb40a2495d5f6d7/rfcs/20191206-tensorflow-lattice-v2.md)
