### ISSUE TITLE
tf.TensorShape should get only one argument

### ISSUE THREAD

**Issue by devavratTomar** [tensorflow/lattice#46]
I received an error when https://github.com/tensorflow/lattice/blob/master/tensorflow_lattice/python/parallel_combination_layer.py#L152 this line was executed by me.

it should be replaced by
`tf.TensorShape([None, ...])`

**Comment by wbakst** [comment]
Thanks for catching this!

**Comment by mmilanifard** [comment]
Fixed in 2.0.4.
