### ISSUE TITLE
Unable to import in Jupyter Notebook

### ISSUE THREAD

**Issue by ken-avco** [tensorflow/lattice#5]
Used pip3 to install on ubuntu machine. Seemed to install fine (tried both globally and a specific env). Am unable to import tensorflow_lattice as tfl in jupyter notebook. I get the error:

No module named 'tensorflow_lattice'

Any ideas where I went wrong? Thanks!

**Comment by si-you** [comment]
Based on the error message, I suspect that your jupyter notebook is linked to ipython kernel that doesn't know how to locate tensorflow_lattice libraries.
There's a way to install ipython notebook kernel to your specific environment.

1. source <your_virtual_env_path>/bin/activate
2. pip install --upgrade ipykernel
3. python -m ipykernel install --user --name tf-lattice
4. jupyter notebook

Could you try this and check whether it works or not?

**Comment by ken-avco** [comment]
that did the trick! Thank you so much!!

**Comment by si-you** [comment]
Great! Let me close this.
