### ISSUE TITLE
Saving and loading model via keras interface

### ISSUE THREAD

**Issue by majkee15** [tensorflow/lattice#52]
Hi,

I have constructed a simple sequential model via TFL and although saving via model.save('file_name.h5') works fine, it is impossible to load with keras.models.load_model('h.h5') yielding "ValueError: Unknown layer: ParallelCombination".

example:
```python
model = keras.models.Sequential()
model.add(combined_calibrators)
model.add(tf.keras.layers.RepeatVector(2))
model.add(lattice)
model.compile(loss=keras.losses.mean_squared_error,
            optimizer=keras.optimizers.Adam(learning_rate=0.001))
model.save('h.h5')

m2 = keras.models.load_model('h.h5')
```

**Comment by mmilanifard** [comment]
When you save/load as h5, you need to provide a custom objects mapping that includes layers that are not part of default keras lib. We provide a helper that includes all custom objects used in our canned models. See details [here](https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects).

```
keras.models.load_model('h.h5', custom_objects=tfl.premade.get_custom_objects())
```
