### ISSUE TITLE
Grammar error

### ISSUE THREAD

**Issue by trulicup** [tensorflow/lattice#60]
_lattice/docs/tutorials/shape_constraints.ipynb_

under _Shape Constraints_ in _Diminishing Returns_

It should read:
Diminishing returns means that the marginal gain of increasing **a certain feature** value will decrease as we increase the value.

Not this:
Diminishing returns means that the marginal gain of increasing **certain a feature** value will decrease as we increase the value.

It's not a big deal but i was really confused for a minute trying to understand what it meant.
Also is there a better place to bring up minor things like this?

**Comment by mmilanifard** [comment]
Thanks for reporting. The fix will show up in the next release.
