### ISSUE TITLE
Crossed column support in TF Lattice

### ISSUE THREAD

**Issue by as24-asingla** [tensorflow/lattice#61]
Hi, I am relatively new to tensorflow lattice and find it really powerful. I have couple of points to which I could not get any answer to.

- Does TF lattice input support crossed feature column or any timeline when that would be possible?

- Does TF lattice support a trained model as a keras layer input?

Thanks in advance.

**Comment by mmilanifard** [comment]
We do not have immediate plans to support other feature column types. But you can always construct models using our keras layers which would let you use any combinations with of other layers and feature columns. You can also use our [keras premade models](https://www.tensorflow.org/lattice/tutorials/premade_models) and mix and match with other models and layers as needed.
