### ISSUE TITLE
Nonuniform lattice cells

### ISSUE THREAD

**Issue by LumingSun** [tensorflow/lattice#67]
Is it possible to use nonuniform lattice cells with tensorflow lattice, i.e., to set lattice node unevenly distributed along each feature like the idea in the paper _Nonuniform Lattice Regression for Modeling the Camera Imaging Pipeline_.

**Comment by mmilanifard** [comment]
We don't support non-uniform lattices. The closest potential solution is to use a calibrated lattice structure, were you have piece-wise linear functions feeding into a lattice. The granularity of the overall composition changes over the range of inputs, but the non-uniformity is coordinate-wise independent across inputs. In 2d it looks something like this: 

![lattice](https://user-images.githubusercontent.com/32752864/115475239-0dc46900-a1f4-11eb-9243-93748c817535.png)
