### ISSUE TITLE
Info: Is there any way to plot feature importance in lattice models?

### ISSUE THREAD

**Issue by as24-asingla** [tensorflow/lattice#70]
Hi,
We are using TF lattice model over a bunch of features. However, we want to understand if there is a way to plot feature importance in TF lattice?
Thanks in advance :)

**Comment by mmilanifard** [comment]
There is no feature importance tool in the TFL codebase, but you can try **partial dependence plots** in the [What-If tool](https://www.tensorflow.org/tensorboard/what_if_tool) as part of tensorboard in TFX, or standalone invocation in colab (see [examples](https://pair-code.github.io/what-if-tool/explore/#notebook)).

![image](https://user-images.githubusercontent.com/32752864/118545221-2ba9be80-b70b-11eb-8720-cbcaf49fa3c2.png)
Generally speaking, the slope/variation of the PDP plot is a measure of feature importance.
