### ISSUE TITLE
How to select number of keypoints?

### ISSUE THREAD

**Issue by SaiAditya2595** [tensorflow/lattice#71]
I have seen some  TF lattice files where pwl_calibration_num_keypoints are 5,10,20. How to select and set these keypoints?

**Comment by mmilanifard** [comment]
These, among other hyper-parameters, are often chosen using cross-validation on a held out data set. The model complexity increases with the number of trained calibration keypoints, so there might be overfitting if the number is too large for the size of the training dataset.
